### ISSUE TITLE
Please provide a policy document for the ec2 instance

### ISSUE THREAD

**Issue by arpansolanki** [awslabs/dynamodb-continuous-backup#10]
There should be a sample policy document provided which ec2 instance can assume. That will help make the documentation better.

**Comment by BMR59920** [comment]
Hi, Arpan. Maybe I can help. I have been testing this tool for about a month and I am not aware of a portion that uses an ec2 instance. Could you maybe clarify where it is that you see this tool references that and needs the policy document?

**Comment by arpansolanki** [comment]
Hello,
So i had spin up an ec2 instance and cloned the git repo and ran the commands 
./build.sh <config file name>
and
python deploy.py -config-file <config file name>

While running those commands from ec2, i ran into privilage/access issues so i had to create a role with those privs and spin up an ec2  instance again using that role and everything worked fine after that.

Is there any other way i should be running this utility?

Thanks,
Arpan

**Comment by BMR59920** [comment]
I would (and did) run this all _locally_ on your *NIX system - or on a VM. There are some implied prerequisites that you need. Python 2.7, pip, hjson, shortuuid, boto3, and aws cli access. 

I had to tweak some of these scripts - and you may too.

**Comment by IanMeyers** [comment]
I've added a section to the README in commit https://github.com/awslabs/dynamodb-continuous-backup/commit/ca6fc4b2a77b5d2aa67c552782cf45b40a55b0d8 which hopefully should help.
