### ISSUE TITLE
What's the best approach to start using this backup method?

### ISSUE THREAD

**Issue by maciejstromich** [awslabs/dynamodb-continuous-backup#13]
Hey,

just a quick question for people who started to use the continuous backup with already created tables. I understand that this backup solution is creating backup files in s3 after an event happened in the database so it means that the majority of data will not be backed up.

did you use Import/Export method to backup everything prior to the installation? and now restore would mean to first import everything from the 1st full backup and then reimport everything from the continuous backup?

**Comment by IanMeyers** [comment]
Sorry you've not had any replies - but yes, you would want to take a full backup using existing methods, and then use this module to do sequence level point in time recovery. You would take this full backup periodically to limit the amount of data that you'd have to 'play forward' into the table to recover.
