### ISSUE TITLE
Change cloudWatchRoleArn Trust Relationship to events.amazonaws.com?

### ISSUE THREAD

**Issue by hoanngu** [awslabs/dynamodb-continuous-backup#14]
In the Appendix for cloudWatchRoleArn (https://github.com/awslabs/dynamodb-continuous-backup#cloudwatchrolearn), should the Trust Relationship be updated from "cloudtrail.amazonaws.com" to "events.amazonaws.com" to coincide withe the architecture change to CloudWatch Events? (https://github.com/awslabs/dynamodb-continuous-backup/commit/5fe5db1f0f6b6b5a2d0726b8d52e01901491e19d)

Thanks,
Hoang

**Comment by IanMeyers** [comment]
Fixed
