### ISSUE TITLE
Deploy script ResourceNotFoundException when setting DynamoDBCreateDelete target

### ISSUE THREAD

**Issue by hoanngu** [awslabs/dynamodb-continuous-backup#15]
When running the deploy.py script, I get the following error:

$ ./deploy.py --config-file config.hjson 
Created new CloudWatch Events Rule arn:aws:events:eu-west-1:xxxxxxxxxxxx:rule/DynamoDBCreateDelete
Using existing DynamoDB Ensure Backup Module at arn:aws:lambda:eu-west-1:xxxxxxxxxxxx:function:EnsureDynamoBackup
Traceback (most recent call last):
  File "./deploy.py", line 187, in <module>
    configure_backup(config['region'], config['cloudWatchRoleArn'], config['lambdaExecRoleArn'], args.redeploy)
  File "./deploy.py", line 167, in configure_backup
    lambda_arn = deploy_lambda_function(region, lambda_role_arn, cwe_rule_arn, redeploy_lambda)
  File "./deploy.py", line 111, in deploy_lambda_function
    response_doc = json.loads(lambda_client.get_policy(FunctionName=LAMBDA_FUNCTION_NAME)['Policy'])
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 251, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 537, in _make_api_call
    raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ResourceNotFoundException) when calling the GetPolicy operation: The resource you requested does not exist.

Current solution is to go into AWS console and manually set the Target to EnsureDynamoBackup for the DynamoDBCreateDelete rule.

**Comment by Altavious** [comment]
Also seeing this.

**Comment by IanMeyers** [comment]
This should now be fixed in https://github.com/awslabs/dynamodb-continuous-backup/commit/c10c4738768adfeae7b759045fcab71ecaa5f361

**Comment by hoanngu** [comment]
Resolved on my setup. Thanks, Ian!
