### ISSUE TITLE
lambdaExecRoleArn missing permissions.

### ISSUE THREAD

**Issue by Altavious** [awslabs/dynamodb-continuous-backup#17]
I ran into a couple permissions issues while using the iam roles in the readme, my latest version for the lambda function needed the following added:

                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents",
                "lambda:CreateFunction",
                "iam:passrole"

**Comment by IanMeyers** [comment]
Fixed in docs
