### ISSUE TITLE
Missing permissions for S3 bucket in us-west-2

### ISSUE THREAD

**Issue by Altavious** [awslabs/dynamodb-continuous-backup#18]
Running into an issue accessing the LambdaStreamToFirehose file in us-west-2, think maybe the bucket policy isn't open:

 error occurred (AccessDeniedException) when calling the CreateFunction operation: Your access has been denied by S3, please make sure your request credentials have permission to GetObject for aws-lambda-streams-to-firehose-us-west-2/LambdaStreamToFirehose-1.4.1.zip. S3 Error Code: AccessDenied. S3 Error Message: Access Denied:

**Comment by bfsrjose** [comment]
Read through the closed issues, S3:Get* & S#:List* are in the iam role that I have deployed for the lambda exec.

**Comment by Altavious** [comment]
Appears to be version specific, output of s3 cp:

$ aws --region us-west-2 s3 cp s3://aws-lambda-streams-to-firehose-us-west-2/LambdaStreamToFirehose-1.4.1.zip lam.zip
A client error (403) occurred when calling the HeadObject operation: Forbidden
Completed 1 part(s) with ... file(s) remaining
$ aws --region us-west-2 s3 cp s3://aws-lambda-streams-to-firehose-us-west-2/LambdaStreamToFirehose-1.3.5.zip lam.zip
download: s3://aws-lambda-streams-to-firehose-us-west-2/LambdaStreamToFirehose-1.3.5.zip to ./lam.zip
$ ls
lam.zip

**Comment by IanMeyers** [comment]
This should now be resolved. sorry for the trouble

**Comment by Altavious** [comment]
No prob.
