### ISSUE TITLE
Naming/versioning issue during deployment

### ISSUE THREAD

**Issue by Altavious** [awslabs/dynamodb-continuous-backup#19]
The build.sh file creates a version of dynamodb_continuous_backup.zip with a version number at the end. deploy_lambda_function is looking for one without (../dist/dynamodb_continuous_backup.zip).

**Comment by IanMeyers** [comment]
Fixed in https://github.com/awslabs/dynamodb-continuous-backup/commit/45d12bc6a2b8f36abb256af5fb39adac616bc96c
