### ISSUE TITLE
Need help with initial IAM role permissions - cloudTrailRoleArn

### ISSUE THREAD

**Issue by peimurphy** [awslabs/dynamodb-continuous-backup#2]
I am trying to deploy this in us-east-1 region and receiving the follow error when I run  ./deploy.py --config-file config.hjson  after creating the 3 roles. For the cloudTrailRoleArn, I updated the AWS account ID and swapped eu-west-1 to us-east-1 and added as inline IAM policy. Do I need any other IAM trust relationships?

An error occurred (InvalidCloudWatchLogsRoleArnException) when calling the UpdateTrail operation: Access denied. Check the trust relationships for your role.

Perhaps a bit clearer setup docs here on the IAM roles?

**Comment by IanMeyers** [comment]
Thanks for your note. You are right that the trust relationships for each role are not documented. Will add that to the README now.

**Comment by IanMeyers** [comment]
Added this in https://github.com/awslabs/dynamodb-continuous-backup/commit/209bb87d5ad4b90bab5fd2d71db7e50fee44dd00. Can you please check your settings and then provide any further details on errors you see?

**Comment by peimurphy** [comment]
Success - “Created Subscription Filter for DynamoDB only events on CloudTrail Log Stream”

I had the one correct for the lambdaExecRoleArn but the other 2 needed tweaks! Thanks - Will let you know how it goes today with the rest of my testing.
