### ISSUE TITLE
Does not work 

### ISSUE THREAD

**Issue by hemantborole** [awslabs/dynamodb-continuous-backup#23]
Just following the doc, and it does seem to work out of the box. First had to create the roles, and managed to get all the way to creating the dynamodb tables.
After the table creation, I see cloudwatch error on lambda execution, but the lambda log group is not created so it is hard to tell why the lambda execution failed. So manually tested the lambda function, and it fails with

 "errorMessage": "Unable to import module 'index'"

At this point, I am giving up on trying more alternatives. Will come back to this later to figure out whats going on, but definitely need more instructions in the doc to make this work.

**Comment by arj22** [comment]
Lambda function test is successful for me. But the firehose delivery stream is not created. I could see the logs when I test the function but not when I create a table.

**Comment by grayaii** [comment]
@hemantborole I just got bit by that too.  I fixed it by "cd src" and then running all the commands from there.  I created an issue (which i just closed) here: https://github.com/awslabs/dynamodb-continuous-backup/issues/26

**Comment by SudBisht** [comment]
Lambda function test is not succeeded also cloudwatch Log Streams not created

"errorMessage": "Unable to import module 'lambda_function'"

**Comment by IanMeyers** [comment]
Sorry it's taken me so long to respond. Is this still an issue for you?

**Comment by SudBisht** [comment]
Working fine.
