### ISSUE TITLE
firehose delivery stream not created

### ISSUE THREAD

**Issue by arj22** [awslabs/dynamodb-continuous-backup#24]
Hi Ian,

I have followed the steps and everything worked fine until deploying Lambda function. But when I create a table, firehose delivery stream is not created and I do not see any log output for EnsureDynamoBackup. "There was an error loading Log streams". I have double checked every step and everything seems fine. Any idea what could have gone wrong with the firehose stream?

Thanks,
Anudeep

**Comment by rjuliano** [comment]
@AnudeepReddyJ21 this should address the issue you were running into

**Comment by arj22** [comment]
@rjuliano thank you! also it would be great if you could specifically mention in the documentation that CloudTrail must be enabled for this to work. There is sentence "This module requires 3 roles in order to deliver data between **CloudTrail,** CloudWatch and Amazon Kinesis on your behalf. " But it didn't grab my attention for some reason.
