### ISSUE TITLE
EnsureDynamoBackup is not authorized to perform: lambda:DeleteEventSourceMapping

### ISSUE THREAD

**Issue by yunw** [awslabs/dynamodb-continuous-backup#29]
While I am doing "delete_table" to dynamodb, the cloudwatch log says:

`ClientError: An error occurred (AccessDeniedException) when calling the DeleteEventSourceMapping operation: User: arn:aws:sts::<account>:assumed-role/LambdaExecRole/EnsureDynamoBackup is not authorized to perform: lambda:DeleteEventSourceMapping on resource: arn:aws:lambda:us-west-2:<account>:event-source-mapping`

I tried adding "lambda:DeleteEventSourceMapping" to the LambdaExecRole IAM role. but still get the same error.

**Comment by IanMeyers** [comment]
I've adding the missing permissions to the README.md now, specifically:

```
"firehose:DeleteDeliveryStream",
"lambda:DeleteEventSourceMapping"
```

Please re-open this issue if the problem persists.
