### ISSUE TITLE
Lambda streams to to firehose bucket not availlable in all regions

### ISSUE THREAD

**Issue by webratz** [awslabs/dynamodb-continuous-backup#3]
Hi,

I'm deploying this in `eu-west-1` and succeeded pretty far, altough when running `provision_tables.py` I receive the following error message

> An error occurred (InvalidParameterValueException) when calling the CreateFunction operation: Error occurred while GetObject. S3 Error Code: PermanentRedirect. S3 Error Message: The bucket is in this region: null. Please use this region to retry the request

According to boto3 docs at http://boto3.readthedocs.io/en/latest/reference/services/lambda.html#Lambda.Client.create_function regarding the create_function call it says:

> This bucket must reside in the same AWS region where you are creating the Lambda function.

This seems to be the reason for the error above.
So is there an easy way to get this setup deployed in eu-west-1 without creating an own s3 bucket and changing the code to point to the new location?

**Comment by IanMeyers** [comment]
Hi Steve - sorry about that. I've pushed an extension which now supports eu-west-1, and will roll out the rest of the regions presently. Please let me know if this new version doesn't work. It will require that you rebuild and redploy the module.

**Comment by webratz** [comment]
this seems to work now

**Comment by sketchedpaper** [comment]
We're running into the same error in us-west-2 with the most recent update. Should all regions be working at this point?

**Comment by IanMeyers** [comment]
Yes, they absolutely should. All us regions will expect to resolve to the bucket aws-lambda-streams-to-firehose-us-std. Can you paste the error that you are getting in the logs?

Thx!

**Comment by IanMeyers** [comment]
Sorry - understand the issue now. 2 mins.

**Comment by IanMeyers** [comment]
This should be fixed now - please update from github, rebuild with your config file and redeploy.

**Comment by BMR59920** [comment]
This seems to have been addressed for us-west-2, however there is another issue with accessing the bucket that houses LambdaStreamToFirehose-1.3.5.zip

https://github.com/awslabs/dynamodb-continuous-backup/issues/7

**Comment by IanMeyers** [comment]
Agreed - I believe this is now closed - the recommended IAM policy for `LambdaExecRole` didn't include `s3::Get*` and `List*`. Closing this one and we'll track issue 7.
