### ISSUE TITLE
Please use GIT tags to match the tags in the script(s)

### ISSUE THREAD

**Issue by mkaurin** [awslabs/dynamodb-continuous-backup#31]
As a user of this project, I want to have control over the version my deployment script provisions this project.

Right now, I have to do it via commit IDs, which is not user friendly.

I would appreciate if the GIT tags would match the version mentioned in the build.sh or similar.

**Comment by mkaurin** [comment]
Example [commit](https://github.com/awslabs/dynamodb-continuous-backup/commit/2c9e3ff7d3d864483bb3273ed516cfff137380ea) with versioning mentioned

**Comment by IanMeyers** [comment]
Thanks for the feedback. Will look to support the issue you've raised.

**Comment by IanMeyers** [comment]
Wanted to also pick up on the issue you raised via support. The script you've run, which does include an account ID which is not linked to your runtime, is just an integration test and doesn't represent the production use case for the application. Please let us know if you are having any issues after following the setup guide.
