### ISSUE TITLE
S3 error

### ISSUE THREAD

**Issue by marc-at** [awslabs/dynamodb-continuous-backup#34]
Whether I am running provision_tables or creating new tables, I keep getting the following error.  Perhaps I have configured something incorrectly, but I believe I properly followed the docs and created the IAM roles in the README.

Resolved Firehose Delivery Stream ARN: arn:aws:firehose:us-east-1:<account>:deliverystream/<table-name>
Deploying LambdaStreamToFirehose/LambdaStreamToFirehose-1.4.5.zip from s3://awslabs-code-us-std
Exception while provisioning table <table-name>
An error occurred (InvalidParameterValueException) when calling the CreateFunction operation: Error occurred while GetObject. S3 Error Code: NoSuchBucket. S3 Error Message: The specified bucket does not exist

I have created the "firehoseDeliveryBucket" and the "firehoseDeliveryPrefix" from the config.hjson file.  I have also granted access to that bucket to the "firehoseDeliveryRoleArn".  

Is there somewhere else I can look?

Am I supposed to deploy LambdaStreamToFirehose-1.4.5.zip to awslabs-code-us-std S3 bucket?

Thank you.

**Comment by millergd** [comment]
Same error here. I believe that the bucket they claim to "not exist" is actually the "s3://awslabs-code-us-std" that you are deploying from, not the one in your config.hjson file.

At this point, I don't know how to debug since that seems to be something on a remote server that I don't have control over.

**Comment by millergd** [comment]
My solution to this was to build my own .zip of the lambda function, store it in an S3 bucket, and then point the `dynamo_continuous_backup.py` file to the new .zip file.

To build your own .zip file, clone the repo (https://github.com/awslabs/lambda-streams-to-firehose) and run `./build.sh.` To point the script to the new .zip file, edit the `lambda_client.create_function(...)` call near line 296 and hard-code the S3Bucket and S3Key values. 

As a side note, I am also working from region us-east-1. Apparently there is a conditional statement in the script that if you are working from this region and only this region, it will change it to 'us-std' and give you your exact error. After fixing this issue, I then got 'access denied' errors. But the steps outlined above should fix that as well.

**Comment by IanMeyers** [comment]
See the issue all - sorry for this. Will fix shortly.

**Comment by IanMeyers** [comment]
This should now be fixed in version 1.4, from https://github.com/awslabs/dynamodb-continuous-backup/commit/ddde2ca9979c93b0185d373211cc8c3f72aca3a3

**Comment by comtaler** [comment]
With the fix, I got permission error:

> An error occurred (AccessDeniedException) when calling the CreateFunction operation: Your access has been denied by S3, please make sure your request credentials have permission to GetObject for awslabs-code-us-east-1/LambdaStreamToFirehose/LambdaStreamToFirehose-1.4.5.zip. S3 Error Code: AccessDenied. S3 Error Message: Access Denied: ClientError
> Traceback (most recent call last):
> File "/var/task/index.py", line 38, in event_handler
> backup.configure_table(dynamo_table_name)
> File "/var/task/dynamo_continuous_backup.py", line 379, in configure_table
> ensure_update_stream_event_source(dynamo_stream_arn)
> File "/var/task/dynamo_continuous_backup.py", line 250, in ensure_update_stream_event_source
> function_arn = ensure_lambda_streams_to_firehose()
> File "/var/task/dynamo_continuous_backup.py", line 311, in ensure_lambda_streams_to_firehose
> raise e
> ClientError: An error occurred (AccessDeniedException) when calling the CreateFunction operation: Your access has been denied by S3, please make sure your request credentials have permission to GetObject for awslabs-code-us-east-1/LambdaStreamToFirehose/LambdaStreamToFirehose-1.4.5.zip. S3 Error Code: AccessDenied. S3 Error Message: Access Denied
>

**Comment by comtaler** [comment]
I tried "us-east-1" and "eu-west-1" and they both failed with the same error. But if I point it to "us-west-2", It works.

**Comment by IanMeyers** [comment]
Looks like there was a strange wobble with permissions on these objects in S3. Can you please retry?

**Comment by clicktravel-steffan** [comment]
I had the same error as comtaler with "eu-west-1". To work around this, I downloaded a binary from https://github.com/awslabs/lambda-streams-to-firehose/tree/master/dist , uploaded to a bucket and edited the `dynamo_continuous_backup.py` as suggested by millergd.
