### ISSUE TITLE
Deploy.py doesn't work like it is stated in the README

### ISSUE THREAD

**Issue by aligg73** [awslabs/dynamodb-continuous-backup#36]
Hi,

Trying to deploy after succesfull build, by:
`./deploy.py config.hjson`

but get this error:
deploy.py: error: unrecognized arguments: config.hjson

**Comment by jasondavis25** [comment]
try `./deploy.py --config-file config.hjson`

**Comment by IanMeyers** [comment]
Fixed in https://github.com/awslabs/dynamodb-continuous-backup/commit/2c7e9a4406bd097abd416685a710651ac61642ae
