### ISSUE TITLE
setup_existing_tables.py never completes when number of tables > 100

### ISSUE THREAD

**Issue by BMR59920** [awslabs/dynamodb-continuous-backup#4]
In our environment, we have > 300 dynamo tables. The query in setup_existing_tables.py seems to  repeatedly attempt to get the table names, but cannot. It only seems to return the first 100.

**Comment by IanMeyers** [comment]
Can you resync to https://github.com/awslabs/dynamodb-continuous-backup/commit/376f8f9f39bad40a6060cc79c3466e24c20a51b2 and retest? This should now be fixed.

**Comment by BMR59920** [comment]
This causes a python error : Invalid length for parameter ExclusiveStartTableName, value: 0, valid range: 3-inf

Gist : https://gist.github.com/BMR59920/847e884da203a73032b8b7e8989d03af

**Comment by IanMeyers** [comment]
Derp - sorry - fixed in https://github.com/awslabs/dynamodb-continuous-backup/commit/b5a28e906a535cc8b3573f937eb4b235e87b0762

**Comment by BMR59920** [comment]
Thank you. b5a28e9 addresses this issue.
