### ISSUE TITLE
Support for CLI Profiles on Deploy.py

### ISSUE THREAD

**Issue by jamesrenaud** [awslabs/dynamodb-continuous-backup#40]
We currently leverage a multi-account structure, and I'd like to deploy this to an account in which I need to use a CLI profile to access via command line. As far as I can tell there's currently no support as part of the deploy.py to specify a CLI profile to utilize.

**Comment by IanMeyers** [comment]
Hello - if you `export AWS_PROFILE=<profile name>`, does that work for you? This environment variable should override anything else but still apply arguments as supplied to the utility.

**Comment by jamesrenaud** [comment]
Yep that did it! Thanks @IanMeyers
