### ISSUE TITLE
Table names longer than 64 characters cause ValidationException

### ISSUE THREAD

**Issue by BMR59920** [awslabs/dynamodb-continuous-backup#5]
11/01 09:40 > python provision_tables.py provisioning_whitelist_LOCAL.hjson
Building Table List for Processing from provisioning_whitelist_LOCAL.hjson
Loaded configuration from config.hjson
current_region: us-west-2
...
Resolved DynamoDB Stream ARN: arn:aws:dynamodb:us-west-2:102671227235:table/bobStackDev-DynamoDBDevCMV1-167S2NF9HGV14-configurationSpec-115NOKVJHVP3H/stream/2016-11-01T16:23:56.785
Exception while provisioning table bobStackDev-DynamoDBDevCMV1-167S2NF9HGV14-configurationSpec-115NOKVJHVP3H
An error occurred (ValidationException) when calling the CreateDeliveryStream operation: 1 validation error detected: Value 'pdhStackDev-DynamoDBDevCMV1-167S2NF9HGV14-configurationSpec-115NOKVJHVP3H' at 'deliveryStreamName' failed to satisfy constraint: Member must have length less than or equal to 64
Proceeding...

I realize that this is a limitation of the DeliveryStreamName in Kinesis Firehose.

**Comment by IanMeyers** [comment]
Fixed in https://github.com/awslabs/dynamodb-continuous-backup/commit/d1a28704c3ceabafeed79662ef2a57aa794188fa

**Comment by BMR59920** [comment]
This is fixed. Thank you.
